scripts/setup.sh

- gem install pivotal_git_scripts only does current user

Installing git-pair at system level

---

scripts/osx-settings.sh
scripts/setup.sh

There is alot that https://github.com/pivotal-sprout/sprout-osx-settings does for us, this is the beginning of incorporating that goodness

Display date and auto hide dock

---

scripts/setup.sh

Seems like we were using a fork

Use the main Bash-it git repo

---

files/add_user_initials_to_git_prompt_info.bash
scripts/configuration-bash.sh

-This was tested on a fresh install of workstation-setup

Adds who is paired to the command prompt

---

scripts/git-aliases.sh

This commit was tested on a fresh install of workstation-setup on a newly imaged machine

Adds gst to aliases for git status

---

files/bobby_pivotal/bobby_pivotal.theme.bash
scripts/configuration-bash.sh

- I'm not sure how to easily modify the .bash_profile's export BASH_IT_THEME='bobby' from the commandline

Brings in classic bobby pivotal theme

---

scripts/git.sh

This fixes issue #6 
@mcwumbly Please merge if you agree.
Thanks,
\- Ash
see:
https://groups.google.com/forum/#!topic/binary-transparency/f-BI4o8HZW0
https://github.com/pivotal/workstation-setup/issues/6

add git integrity checks

---

designer.sh
engineer.sh

A simple fix to issue #24 
@professor This should do, correct? Please click the merge button if you think this fixes the issue.
Thanks,
\- Ash

force running as sudo to avoid prompts in other scripts

---

files/.irbrc
scripts/ruby.sh

see:
https://github.com/rbenv/ruby-build/wiki#trouble-with-irb-or-pry
fixes #37

install ~/.irbrc and readline library for irb history

---

designer.sh
engineer.sh
scripts/homebrew.sh
scripts/setup.sh
scripts/teardown.sh
scripts/xcode-license.sh

Initial prompt for password

---

files/com.googlecode.iterm2.plist

* Updated for iTerm 3.0
* Tomorrow Night theme
* Opening new window or tab retains same directory
* 18pt Menlo font
* Unlimited scrollback
* Silent bell
* Visual bell

Update iTerm preferences to use nicer defaults

---

scripts/configuration-bash.sh
scripts/ruby.sh

Use bash-it rbenv plugin in place of manual loading of rbenv via bash_profile

Use bash-it rbenv plugin

---

README.md
data-engineer.sh
labs-engineer.sh
scripts/applications-data-engineer.sh
scripts/setup.sh

Solves issue https://github.com/pivotal/workstation-setup/issues/72

Adding tools used by the Data R&D organization

---

scripts/configuration-bash.sh

git clone is already specifying its destination
Signed-off-by: C.J. Jameson <cjameson@pivotal.io>

Remove unnecessary pushd / popd

---

.pairs
scripts/applications-common.sh
scripts/applications-designer.sh

Don't halt when cask install fails

---

scripts/applications-data-engineer.sh

Currently we get a can't find ./scripts/configurations.sh error

Fixes script to return to correct working directory

---

scripts/applications-labs-engineer.sh
scripts/setup.sh

move ruby and node to labs-only

---

scripts/applications-data-engineer.sh

Adds ninja for orca

---

scripts/applications-data-engineer.sh

Solves https://github.com/pivotal/workstation-setup/issues/142

Removes autoconf since macOS Sierra comes with it

---

scripts/applications-labs-engineer.sh
scripts/node-packages.sh
scripts/node.sh

This will make installing specific languages easier when there is just one file for node

Combines node with node packages

---

scripts/c.sh
scripts/configurations.sh
scripts/download-pivotal-ide-prefs.sh
scripts/golang.sh
scripts/java.sh
scripts/ruby.sh

By moving this configuration into each programming language, we can opt in or opt out of specific programming languages during installation

Moves pivotal-ide-prefs configuation into each programming language

---

scripts/applications-common.sh
scripts/git.sh
scripts/setup.sh

Solves https://github.com/pivotal/workstation-setup/issues/132

Removes zoomus password prompt

---

scripts/java.sh

Solves https://github.com/pivotal/workstation-setup/issues/97

Guard against pre-installed intellij

---

files/add_user_initials_to_git_prompt_info.bash
scripts/finished.sh

While setting up git-together, I ran into some minor speed bumps. Hopefully this change should make it easier for the next person to get set up.
@professor can you review, or nominate a reviewer?

Refactor git_prompt_info and fix git-together setup steps

---

scripts/applications-common.sh

macOS now ships with Night Shift
Solves https://github.com/pivotal/workstation-setup/issues/163

Removes flux

---

scripts/golang.sh

https://blog.jetbrains.com/go/2017/11/02/announcing-goland-former-gogland-eap-18-final-product-name-templates-support-and-more/
Signed-off-by: Shoaib Lari <slari@pivotal.io>

Rename the golang editor from JetBrains

---

scripts/opt-in/java-tools.sh

Signed-off-by: Yoann Galentin <yoann.galentin@orange.com>

Install Maven Deluxe instead of just Maven

---

README.md

Authored-by: C.J. Jameson <cjameson@pivotal.io>
responding to https://github.com/pivotal/workstation-setup/commit/f8341199e0d79a6b4069da640fd3224953be3e19 from @professor

Indicate in readme a little flexibility in macOS version

---

scripts/common/git.sh

Adds git-hooks-core for detecting credential leaks

---

scripts/common/finished.sh
scripts/common/git.sh

Co-authored-by: Todd Sedano <tsedano@pivotal.io>
Co-authored-by: Xin Zhang <xzhang@pivotal.io>

Adds git-author

---

scripts/common/applications-common.sh

Toolbox manages every Jetbrains product installs and updates.
(For the conversation around this commit, see
https://github.com/Pivotal/workstation-setup/pull/179)
Signed-off-by: Yoann Galentin <yoann.galentin@orange.com>

Install Jetbrains Toolbox

---

files/cf_cli.completion.bash
scripts/common/configuration-bash.sh

Use bash-it completion to add CF cli autocomplete.

Add simple Cloud foundry cli autocomplete

---

scripts/common/applications-common.sh

Installs quicklook-json, a QuickLook plugin that gives QuickLook the ability to display JSON files properly.

Install quicklook-json

---

scripts/common/configuration-bash.sh

Solves https://github.com/pivotal/workstation-setup/issues/248

Adds BASH_IT environment variable

---

scripts/common/applications-common.sh

Fixes https://github.com/pivotal/workstation-setup/issues/236

Removes skype

---

scripts/common/git-aliases.sh

@amilkh - we talked about this earlier today.
Authored-by: Ben Christel <bchristel@pivotal.io>

Alias git cherry-pick to cp

---

scripts/opt-in/java8.sh

This will also reference the manual download URL for JDK 8u211/8u212
Fixes #259

Remove Java 8 installation

---

README.md

Remove mention of java8 in the docs

---

README.md
scripts/opt-in/kubernetes.sh
scripts/opt-in/terraform.sh

Hey all!
I just wanted to add some common tooling for Platform Engineers/Solutions Architects. We share much of the same common tooling with just a few differences. 
Let me know if there are any questions!

solutions architect setup

---

README.md
scripts/opt-in/concourse.sh

Hi! 
I piggy backed the commit from Salamandastron1 to include Concourse into the Solutions Architect  option as this may be useful to other SA's using this script. 
Let me know if there are any questions!

added concourse for SA option

---

.pairs

- Update email from Pivotal to VMware
- Remove alumni: John, Stephen, Josh, and Brian
- Update name (Cedar)
- Add me

Clean up .pairs file

---

scripts/common/developer-utilities.sh
scripts/common/oh-my-zsh.sh
scripts/opt-in/docker.sh
scripts/opt-in/java8.sh

Mostly avoiding errors, early exits, and old bash configuration.

Various fixes

---

scripts/common/homebrew.sh

Detecting that Homebrew needs env-vars set and following their own instructions to do so

Fix homebrew install
