pivotal/workstation-setup

scripts/git.sh

rowanj's GitX-dev fork is more well-maintained than the original GitX, and has several
improved features.
https://rowanj.github.io/gitx/

Install rowanj-gitx instead of regular gitx

---

scripts/configuration-osx.sh

- very handy on an iOS project or when someone wants to charge their phone.

Stop Photos from opening automatically

---

scripts/configuration-osx.sh

I tried to run workstation-setup on my Mac at home, and this was the only real hiccup I ran into.

Make OSX configuration work for users who aren't named 'pivotal'

---

README.md

Shell prompts in examples make it more difficult to cut/paste the entire code block. Removing these so that all the commands can be run at once.

Remove shell prompt to make cut/paste easier

---

scripts/git.sh

The default behavior of modern Git versions is to only push the current branch when running `git push`.
This removes a line that was instead setting us up on the previous behavior of pushing all branches with matching names.

Use default setting for `push.default` in Git

---

.pairs
scripts/applications-common.sh

Not sure what the process is for determining/requesting what goes into this repository, but a number of devs here like using `ag` as an alternative to `grep` and `find`.  Totally cool with this making it in or not.
https://github.com/ggreer/the_silver_searcher

add ag (Silver Searcher) to engineering apps

---

scripts/setup.sh

Adds the missing 'then' keyword to fix syntax error
```
if [ conditional expression ]
then
statement1
statement2
.
fi
```

Add then to fix syntax error in if statement

---

scripts/configuration-bash.sh

- it will scan ~/.ssh/config, ~.ssh/known_host, and /etc/hosts

Enable bash tab completion for ssh

---

scripts/applications-common.sh

Lately, MacVim from the cask has been good enough and it's easier to install without requiring XCode.
Any objections?

Install MacVim from cask

---

scripts/configurations.sh

It doesn't work anymore in macOS Sierra
See #94

Remove accessibility autoconfiguation for ShiftIt

---

scripts/java.sh

Projects generally don't need these tools locally while developing.
If someone wants these, you should add them via a Brewfile or something
else specific to your project.
Signed-off-by: Grant Hutchins <ghutchins@pivotal.io>

Remove nexus and jenkins from java.sh

---

README.md
scripts/homebrew.sh

- It fails on El Capitan because it demands the latest version
of Xcode, which El Capitan can't run.
- Since workstation-setup is usually run on a fresh install of the
OS, we think it's unlikely that brew doctor will detect real problems
for most users. Users who do run into problems can run `brew doctor`
themselves.

Remove `brew doctor`.

---

README.md

Fix markdown links in README

---

scripts/applications-common.sh

zoomus is the name of the cask because zoom was already taken and their
url is zoom.us
→ brew cask info zoomus
zoomus: 4.0.29656.0413
https://www.zoom.us/
Not installed
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/zoomus.rb
==> Name
Zoom.us
==> Artifacts
zoomusInstaller.pkg (pkg)

Enable people to communicate with zoom desktop client

---

scripts/applications-data-engineer.sh
scripts/golang.sh

The scripts used to do setup for golang, but didn't install Gogland. This
commit installs Gogland and does the setup in the same script.
Signed-off-by: C.J. Jameson <cjameson@pivotal.io>

Install Gogland

---

scripts/configuration-bash.sh
scripts/ruby.sh

The script configuration-bash.sh enabled the rbenv plugin on bash-it.
This change guarantees that it is installed before this happens.
Previously, rbenv would be installed as a later step in the lab-engineer
script which would call ruby.sh. But for the data-engineer script this
did not happen.

Install rbenv before bash-it uses it

---

scripts/configurations.sh

Solves https://github.com/pivotal/workstation-setup/issues/121
Note. This will clone on brand new machines. It will no-op on machines existing with ~/.vim or pivotal_ide_prefs. 
I was tempted to add an else block and do a `git pull -r` to get the latest on these repos, but there could be merge conflicts. Thoughts?

Does not delete previous ~/.vim or pivotal_ide_prefs

---

scripts/configurations.sh

This fixes #126, an issue with the vim configuration part of the setup where it would crash if the directory `~/.vim` already existed and the file `~/.vim/bin/install` was not there.

Fix vim config to not crash the setup

---

scripts/finished.sh

When imaging a new machine, the bootstrap gives us a window of opportunity to set the machine name. If we miss this window of opportunity, I'm often googling on how to set the hostname. This provides a quick reminder when the script ends.

Provides hints on how to set hostname when script finishes

---

scripts/cloud.sh

The only package we don't install from cloudfoundry
homebrew tap is 'credhub-cli'
Signed-off-by: Goutam Tadi <gtadi@pivotal.io>

Install bosh cli bosh-init bbl

---

scripts/cloud.sh

From #134 
https://github.com/pivotal/workstation-setup/pull/134#issuecomment-319862173
You shouldn't need bosh-init any more, as bosh-cli subsumes all features of
bosh-init
if you really want it to be called "bosh", it's just a
`brew install bosh-cli --without-bosh2` away.
Signed-off-by: Jesse Zhang <jzhang@pivotal.io>

Improve installation of bosh cli utils

---

scripts/applications-common.sh

A cask for google drive currently does not exist so removing installation for now.

Remove google drive from common applications

---

scripts/configurations.sh

This error is causing the config script to break. It has been an issue since at least July 24:
https://github.com/pivotal/workstation-setup/issues/133
perhaps loginitems should be removed for now?

Remove loginitems from configurations script

---

scripts/golang.sh

I tested with 1) brew uninstall go, 2) brew install go, 3) run tests and build gpbackup
Solves https://github.com/pivotal/workstation-setup/issues/105

Removes --cross-compile-common flag from go

---

README.md
scripts/setup.sh
scripts/xcode-license.sh

On Sierra, when using git for the first time, it installs the developer tools
Solves https://github.com/pivotal/workstation-setup/issues/113

Removes Xcode dependency for macOS Sierra

---

scripts/applications-common.sh
scripts/setup.sh

This means that the user has one less password to type
Solves https://github.com/pivotal/workstation-setup/issues/132

Relocates zoom.us

---

scripts/ruby.sh

Fixed bug:  If rubymine comes preinstalled, the script would crash.

Guard against pre-installed rubymine

---

scripts/git-aliases.sh

This is necessary for macOS High Sierra.
I'm not sure why this changed in High Sierra. 
Is this the best way to solve this?

Add bash_it enabled directory

---

scripts/setup.sh

- This is in response to the PR done [here](https://github.com/caskroom/homebrew-cask/pull/39883).

Rename `github-desktop` cask to `github`.

---

README.md

Noticed that clicking the links in the README for applications-common.sh or applications-designer.sh resulted in a 404.

Update links to applications-common.sh and applications-designer.sh

---

scripts/opt-in/java-tools.sh
scripts/opt-in/java.sh
scripts/opt-in/java8.sh

This PR moves the java tool installation into a separate script, java-tools.sh. java.sh installs java 9 and then installs the tools. java8.sh installs java 8 and the installs the tools.

Add support for java 8. Move tools to separate script.

---

scripts/opt-in/java8.sh

The java8 script failed on my machine without having tapped old versions. (The current cask installs java 9)

Taps old casks in order to install java8

---

scripts/common/cloud-foundry.sh

See a similar PR to fix another warning message from `cloud-foundry.sh`: https://github.com/cloudfoundry/homebrew-tap/pull/45

Address warning: remove unnecessary flag, continue using new bosh cli

---

scripts/opt-in/golang.sh

Since dep (https://github.com/golang/dep) is the new standard Go dependency management tool and several teams in Data are starting to use it, we want to add it to the default setup.

Add dep to golang install script

---

scripts/common/applications-common.sh

Or would it be even better to just make this a default-on setting? I prefer it.
`brew cask install shiftit` is getting the latest from Github at the current
time (v1.6.5) which fixes https://github.com/fikovnik/ShiftIt/pull/258

Suggest to shiftit afficionados how to get Onsi-like behavior

---

scripts/common/git.sh

At commit d929075137b8d, git-author was added to setup scripts.
The `brew install git-together` from scripts/common/git.sh#L7 depends on
git-together [1].  This dependency installs git-together, and this
causes the command `brew install seattle-beach/tap/git-together` to fail
with the error:
==> Installing git-together from seattle-beach/tap
Error: git-together 0.1.0-alpha.11 is already installed
To upgrade to 0.1.0-alpha.13, run `brew upgrade git-together`
If we switch the order, the git-author dependancy on git-together can be
satisfied by the seattle-beach tap.
[1] https://github.com/pivotal/homebrew-tap/blob/master/git-author.rb#L7

git-author causes seattle-beach git-together install to fail

---

scripts/common/configuration-bash.sh

- this means users profile automatically gets moved to a backup file, which is
what we want in the standard case of running these scripts on a clean machine

Add a switch to bash_it so it does not prompt for confirmation

---

README.md
files/ANALYTICS.md
scripts/helpers/google-analytics.sh
setup.sh

AS a workstation contributor
I WANT to measure usage frequency and patterns
SO THAT I can direct my development efforts most effectively
Our discussion of virtualbox made me wonder who is using this script and what command lines options they are using.  
To measure this, I added two simple curl calls to the setup.sh (using a new helper script).  These two calls will log starting the workstation-setup and finishing the setup by creating an event in Google Analytics.  Obviously, we can compute success rate from this. 
Example output:
```
| 1. | finish_ruby_go_java | 6(50.00%)
| 2. | start_ruby_go_java  | 6(50.00%)
```
The analytics dashboard that I used is under my pivotal account, so I can share with others.  Screenshot of what it looks like: …

Add Google Analytics to track popular arguments

---

scripts/common/git.sh

Running the setup multiple times was failing on High Sierra. First run was fine, subsequent runs are failing due to `$HOME/workspace/git-hooks-core` being present already. Also, we were littering the git config with multiple `core.hookspath` values pointing to that directory.
Changed the script `scripts/common/git.sh`so that it :
- only clones the pivotal-cf/git-hooks-core repo on the first run
- only adds the git config core.hookspath on the first run
- on subsequent runs, pulls the latest changes
Note: one assumption we made is that you will not be changing the git-hooks-core repo locally ; this is why we allow a git pull -r on it.

Make setting up git-hooks-core idempotent

---

scripts/common/homebrew.sh

This pipes a newline into the homebrew installation script to prevent
a pause in the process.
Signed-off-by: Matthew Conger-Eldeen <mcongereldeen@pivotal.io>

Homebrew installation no longer pauses

---

files/add_user_initials_to_git_prompt_info.bash

On my last two projects I've observed that the visualization of the git duet initials will be broken on OSX machines that have run this setup project. Instead of showing the pair initials in one line (such as dn + to) it instead puts a newline after the + sign.
I know it didn't used to do this, and it looks like there was a change that broke it with this commit:
https://github.com/Pivotal/workstation-setup/commit/d8e4bfa99848f8e219d21aa85439ebcbc580a376#diff-ce247062a551e6172d6370799952a8c7
I'm not super great with bash, but reinserting the echo that wraps the git config command appears to resolve the issue.

Fix alignment of git duet initials

---

scripts/opt-in/golang.sh

When I was settings my workstation the script failed and I had to modify the `--ide` property to be able to install goland on my workstation. Hopefully this can help others.

Update ide_prefs to use Goland's new name

---

scripts/common/homebrew.sh

- sentinelone isn't chownable, and this flags silently skips this failure.
- Fixes #240, as per @textbook suggestion.

Homebrew dir: use -f flag when chown'ing /usr/local/bin

---

scripts/common/configuration-bash.sh

Sourcing bash_profile does not reliably work when not running interactively.

Add source of bash_it config file.

---

scripts/opt-in/java8.sh

`caskroom/versions` deprecated in 2018 (Caskroom/caskroom.github.io#68) in favor of `homebrew/cask-versions`.

Update cask versions tap

---

scripts/common/git-aliases.sh

This is a common command that I use all the time on projects, such that I have started adding this alias manually each time I set up a machine

Add git alias for commit --amend --no-edit

---

scripts/opt-in/ios.sh

Includes
- package managers: `carthage`, `cocoapods`
- deployment tools: `fastlane`
- ide: `appcode`

Add opt-in script for iOS tools

---

scripts/common/configuration-osx.sh
scripts/common/git-aliases.sh

check for existence before creating `dockutil` and making the `bash_it/aliases/enabled` directory
instead of naive creation (errors out)

file checks

---

README.md
scripts/common/applications-common.sh
scripts/common/git.sh
scripts/common/homebrew.sh
scripts/opt-in/c.sh
scripts/opt-in/designer.sh
scripts/opt-in/docker.sh
scripts/opt-in/dotnet-tools.sh
scripts/opt-in/dotnet.sh
scripts/opt-in/golang.sh
scripts/opt-in/ios.sh
scripts/opt-in/java-tools.sh
scripts/opt-in/java.sh
scripts/opt-in/python.sh
scripts/opt-in/ruby.sh
setup.sh

Summary of Changes:
1. [Update homebrew installer link](https://brew.sh/) (ruby one is now deprecated)
2. Update homebrew cask syntax ([example](https://formulae.brew.sh/cask/github#default))
3. Reduce the number of commands the user needs to run when setting up from 4 to 1 by &-ing the commands. The -p ensures that any existing workspace directory is not overwritten, so it shouldn't matter if the user runs `mkdir workspace` when they already have that directory. 
Verified these changes by running the workstation setup on a 10.15 mac. 
- No homebrew related errors or warnings
- Casks installed correctly (spot checked Slack and Zoom)

Homebrew Deprecations and Reduce the Number of Setup Commands 

---

scripts/common/finished.sh

I noticed that `git-together` was still referenced in `finished.sh` so I removed the reference.
It's still referenced in `add_user_initials_to_git_prompt_info.bash`, but I left that in there just in case people install a different tool and want this to be visible in their git prompt, though I'm happy to remove it from there too in this PR if we'd like to.

Remove reference to git-together

---

scripts/opt-in/kubernetes.sh

This PR adds a new opt-in script: `Kubernetes.sh`, which installs the following tools useful for developing a Kubernetes application.
- kind
- kubectl
- kustomize
- helm
- skaffold

Add kubernetes.sh opt-in for local k8s setup

---

scripts/common/configuration-osx.sh
scripts/common/git.sh
scripts/opt-in/cred-alert.sh
scripts/opt-in/docker.sh
scripts/opt-in/java.sh

Homebrew on M1 machines installs to `/opt/homebrew`, not `/usr/local` (see Homebrew/brew#9177). So I ended up seeing:
```
hint: Waiting for your editor to close the file... fatal: cannot run /usr/local/bin/vim: No such file or directory
error: unable to start editor '/usr/local/bin/vim'
Please supply the message using either -m or -F option.
```
This uses the `brew --prefix` to look in the right place in either architecture.

Get actual vim location for git editor
